### ISSUE TITLE
How to find the ROI's index - name correspondence?

### ISSUE THREAD

**Issue by Boltzmachine** [kendrickkay/nsdcode#27]
For example, in prf-visualrois, how can I know which index corresponds to region V1d?

**Comment by johnmarktaylor91** [comment]
The files with suffix .ctab have this info, for example:

https://natural-scenes-dataset.s3.amazonaws.com/nsddata/freesurfer/subj01/label/prf-eccrois.mgz.ctab

**Comment by Boltzmachine** [comment]
Thanks. I searched but did not find a Python library to read a `.ctab` file. Do you have any suggestions to read it?
